/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.net.InetSocketAddress;
import java.net.Proxy;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String hostname = "172.26.192.129";
        int port = 7706;
        Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress(hostname, port));
        String url = "https://example.com/";
        OkHttpClient client = new OkHttpClient.Builder().proxy(proxy).build();
        Request.Builder builder = new Request.Builder().url(url);
        Request request = builder.build();
        try {
            Response response = client.newCall(request).execute();
            System.out.println(response.body().string());
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
        System.out.println(new App().getGreeting());
    }
}
